#!/bin/bash

which -s node
if [[ $? != 0 ]] ; then
    echo "Please install node version 9 or higher."
else
    which -s npm
    # TODO: should check for version here
    if [[ $? != 0 ]] ; then
        echo "Please install npm version 5 or higher."
    else
        # TODO: consider proper error messaging for network being offline
        npm install --production > "/dev/null" 2>&1
        cd `dirname $0` > /dev/null
        node ./wpe-merge.js $1 $2
    fi
fi
